#! /bin/bash

################################################################
#
# Copyright (c) 1995-2014 SUSE Linux Products GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING); if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
################################################################

if test $# -ne 2; then
    exit 1
fi

zip="$1"
tar="$2"

tmp=$(mktemp -d)
unzip -q -d "$tmp" -- "$zip" || exit 1
( cd "$tmp" && tar czO * ) >"$tar" || exit 1
rm -r "$tmp"
exit 0
