#!/bin/bash -x

export REPOSDIR=${BUILD_ROOT}/obs_repo
export DEBOOT_ARCH

[ "$BUILD_ARCH" = "i586:i486:i386" ] && DEBOOT_ARCH="i386"
[ "$BUILD_ARCH" = "armv7l" ] && DEBOOT_ARCH="armhf"

if [ -d ${BUILD_ROOT}/.pkgs ]; then
    mkdir -p ${REPOSDIR}/standard/${DEBOOT_ARCH}
    for ORIG in `ls ${BUILD_ROOT}/.pkgs`; do
        DEST=`echo $ORIG | sed -e "s,.deb,-1obs1_${DEBOOT_ARCH}.deb,g"`
        cp ${BUILD_ROOT}/.pkgs/${ORIG} ${REPOSDIR}/standard/${DEBOOT_ARCH}/$DEST
    done
else
    mkdir -p ${BUILD_ROOT}
    ln -s ${PKG_CACHE_DIR} ${BUILD_ROOT}/obs_repo
fi
    mkdir -p ${REPOSDIR}/dists/obs/main/binary-${DEBOOT_ARCH}
    mkdir -p ${REPOSDIR}/cache

# Create apt-ftparchive files
cat >> ${REPOSDIR}/apt-ftparchive-obs.conf << EOF
Dir {
  ArchiveDir "${REPOSDIR}";
  CacheDir "${REPOSDIR}/cache";
};

Default {
  Packages::Compress ". gzip";
  Sources::Compress "gzip";
  Contents::Compress "gzip";
};

TreeDefault {
  BinCacheDB "packages-\$(SECTION)-\$(ARCH).db";
  Directory "standard";
  Packages "\$(DIST)/\$(SECTION)/binary-\$(ARCH)/Packages";
  SrcDirectory "pool/\$(SECTION)";
  Sources "\$(DIST)/\$(SECTION)/source/Sources";
  Contents "\$(DIST)/Contents-\$(ARCH)";
  };

Tree "dists/obs" {
    Sections "main";
    Architectures "${DEBOOT_ARCH}";
}
EOF

cat >> ${REPOSDIR}/obs-release.conf << EOF
APT::FTPArchive::Release::Origin "OBS";
APT::FTPArchive::Release::Label "OBS";
APT::FTPArchive::Release::Suite "obs";
APT::FTPArchive::Release::Codename "obs";
APT::FTPArchive::Release::Architectures "${DEBOOT_ARCH}";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Open Build Server local deb repos";
EOF

apt-ftparchive generate ${REPOSDIR}/apt-ftparchive-obs.conf
apt-ftparchive -c ${REPOSDIR}/obs-release.conf release ${REPOSDIR}/dists/obs/ > ${REPOSDIR}/dists/obs/Release

echo "Done generate repos ..."
