#!/usr/bin/perl -w

################################################################
#
# Copyright (c) 2016 SUSE Linux Products GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING); if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
################################################################

BEGIN {
  unshift @INC, ($::ENV{'BUILD_DIR'} || '/usr/lib/build');
}

use Build;
use strict;

while (<STDIN>) {
  chomp;
  my $pkg = $_;
  my $d = Build::query($pkg, 'evra' => 1, 'buildtime' => 1);
  next unless $d;
  my $buildid = Build::getbuildid($d);
  next unless $buildid;
  open(F, '>', "$pkg.buildid") || next;
  print F "$buildid\n";
  close(F);
}
