#!/usr/bin/python

import websocket
import sys

if len(sys.argv) != 2:
    sys.exit("usage: openstack-console <url>")
ws = websocket.create_connection(sys.argv[1],
                                 header={'Sec-WebSocket-Protocol: binary'})
buf = ''
while True:
    data = ws.recv()
    sys.stdout.write(data)
    if not ws.connected:
        sys.stdout.write("[connection closed]\n")
        break
    buf += data
    buf = buf[-256:]
    if re.searcg("[\r\n]\[\s*[0-9\.]*]\s+reboot: Power down", buf):
        break
ws.close()
