.TH unrpm 1 "(c) 1997-2014 SuSE Linux AG Nuernberg, Germany"
.SH NAME
unrpm \- unpack the contents of one or more rpm files
.SH SYNOPSIS
.B unrpm
.RB [ -v ]
.RB [ -q ]
.I rpm
.RB ...

.SH DESCRIPTION
The \fBunrpm\fP tool unpacks one or more rpm files into the
current directory. The \fB-v\fP option makes it print the filenames
while unpacking, whereas the \fB-q\fP option suppresses any output.

.SH SEE ALSO
.BR rpm2cpio (8),
