#!/bin/bash

################################################################
#
# Copyright (c) 1995-2014 SUSE Linux Products GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING); if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
################################################################

function Usage () {
    echo "Usage: $(basename $0) [-vq] rpm-files...";
    echo "Unpack rpm files in current directory.";
    exit 1
}

CPIO_OPTS="--extract --unconditional --preserve-modification-time --make-directories"

FILES=""
VERBOSE=false
QUIET=false

for i in $* ; do
    case "$i" in
      -v)
	VERBOSE=true
	;;
      -q)
	QUIET=true
	;;
      *)
	FILES="$FILES $i"
	;;
    esac
done

test "$VERBOSE" = "true" && CPIO_OPTS="$CPIO_OPTS --verbose"
test "$QUIET" = "true" && CPIO_OPTS="$CPIO_OPTS --quiet"

test -z "$FILES" && Usage

for f in $FILES; do
    if test "$QUIET" = "false" ; then
	echo -ne "$f:\t"
    fi
    rpm2cpio $f | cpio ${CPIO_OPTS}
done
