#!/usr/bin/perl -w

################################################################
#
# Copyright (c) 1995-2014 SUSE Linux Products GmbH
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program (see the file COPYING); if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#
################################################################

use strict;
use Test::More tests => 9;
use Build;

sub d {
  Build::dist_canon($_[0], $_[1]||'i586');
}

is(d("UnitedLinux 1.0 (x86-64)"),       "ul1-x86_64");
is(d("SuSE SLES-8 (ia64)"),             "sles8-ia64");
is(d("SuSE Linux 8.2 (x86-64)"),        "8.2-x86_64");
is(d("SuSE SLES-9 (x86-64)"),           "sles9-x86_64");
is(d("SUSE Linux 10.1 (PPC64)"),        "10.1-ppc64");
is(d("SUSE Linux Enterprise 10 (PPC)"), "sles10-ppc");
is(d("openSUSE 10.3 (X86-64)"),         "10.3-x86_64");
is(d("SUSE Linux Enterprise 11"),       "sles11-i386");
is(d("openSUSE 11.3"),                  "11.3-i386");
