== About the Build Configuration

The build configuration syntax describes the build environment
used for building packages. It is used to:

* Switch on or off certain features during the build

* Decide which packages are installed during build

* Resolve dependency problems like when there are multiple providers
for a dependency

* Handle user decisions like macro settings

=== Configuration File Syntax

The syntax is basically the same as in RPM spec files. However, it is
independent of the used packaging format. You can use spec file
features like macros or conditions in the configuration.

All lines have the form:

    keyword: arguments

Use `%if` or `%ifarch` if the line should only be used in some condition

Many keywords like `Require` or `BuildFlags` do not replace existing
data, but add to it. This means you can have multiple `BuildFlags`
lines instead of having one line with all the flags you need.

You can prepend an exclamation mark `!` to the argument to remove 
an existing entry from the data.

=== Available Keywords in Project Configuration

The following list contains all the allowed keywords in the project
configuration:

==== BinaryType: TYPE

The binary type is the format of the packages that make up the build
environment. This is usually set automatically depending on the recipe
type and preinstall package list.
Currently understood values are: `rpm`, `deb`, and `arch`.

==== BuildEngine: ENGINE

Use an alternative build engine. Examples are `mock` (for Fedora and
Red Hat) and `debootstrap` (for Debian), `debbuild` (to build debian
packages with spec files), `podman` (container builds).

Here is an example config for `debbuild`:

    Type: spec
    Repotype: debian
    Binarytype: deb
    BuildEngine: debbuild
    Support: pax debbuild

==== BuildFlags: FLAG:VALUE

The BuildFlags keyword defines flags for the build process. The
following values for FLAG are usable.

* vmfstype:TYPE

Defines a specific file system when building inside of a VM. Possible
values are `ext2`, `ext3`, `ext4`, `btrfs`, `xfs`, `reiserfs` (v3).

* vmfsoptions:OPTIONS

Sets options for file system creation. Currently only the `nodirindex`
option is supported, which disables directory indexing for ext file
systems. This makes file ordering inside of directories reproducible
but may have a negative performance impact.

* kiwiprofile:PROFILE

Selects the profiles to build in kiwi appliance builds.

* logidlelimit:SECONDS

Build jobs which do not create any output are aborted after some time.
This flag can be used to modify the limit.

* excludebuild:PACKAGE

Exclude a package from building. If a package builds multiple flavors
("multibuild"), the corresponding flavor can be specified via the
`package:flavor` syntax.

* onlybuild:PACKAGE

This can be used to maintain a whitelist of packages to be built.
All other packages will turn to excluded state (and the old build
results will be erased!).

* ccachetype:TYPE

Defines the ccache implementation, possible values are: `ccache`, `sccache`.

* useccache:PACKAGE

Configure usage of ccache when building the specified package.

* obsgendiff

OBS can run an external program that has access to the current build and
the previously successful result, e.g. to generate a difference or a
changelog from the diff.

build will run all scripts in /usr/lib/build/obsgendiff.d/ on the build
host (not in the %buildroot) when this flag is set. If one of the
scripts fails to run or no scripts are found, then the overall build
fails. I.e. if BuildFlags: obsgendiff is set, then you must provide at
least one script in /usr/lib/build/obsgendiff.d/, otherwise your build
will fail.

A common use case for obsgendiff is to run release-compare after the
build.

* setvcs

Adds the SCM URL to binary results when the package sources are managed
via the scmsync mechanic. The url is written into the VCS tag of rpms
when enabling this functionality.

* sbom:FORMAT

Enables generation of SBOM (Software Bill Of Material) data. Supported
formats are spdx and cyclonedx.

* container-compression-format:FORMAT

Sets a compression format for container layers. Possible values are `gzip`, `zstd`,
`zstd:chunked`. The usage of values other than gzip is only supported by the
podman engine.

* container-build-format:FORMAT

For podman container builds, it specifies the container config format. Possible values
are 'docker' and 'oci'. The default is 'docker'. The 'docker' format allows a few
extensions like ONBUILD, SHELL, DOMAINNAME, COMMENT, HEALTHCHECK amongst others.


==== Constraint: SELECTOR STRING

CAUTION: OBS only

Define build constraints for build jobs. The selector is a
colon-separated list which gets a string assigned. See the build job
constraints page for details.

==== ExpandFlags: FLAG

Flags which modify the behaviour during dependency resolution.

* unorderedimagerepos

The priority of repositories defined in an image build is usually
important. This is to avoid switching repositories when the same package
is available in multiple repositories. However, it might be wanted to
ignore that and just pick the highest version. This can be achieved by
defining this flag

* preinstallexpand

Preinstall also all dependencies of a preinstalled package.
Instead of manually listing all packages for a working package tool
one can just install dependencies of it. However, these might be
more then actually needed depending on the distribution.

* module:NAME-STREAM

Enable Red Hat-specific module support in repo md repositories. By
default, no module is used, so every module needed needs to be
specified in the configuration. To remove a module, add an exclamation mark
(!) as prefix.

* docker-nobasepackages

Do not put the require/support/preinstall packages in the repositories
offered to the container build tool. This should have been the default.

* kiwi-nobasepackages

Do not put the require/support/preinstall packages in the repositories
offered to the kiwi build tool. This should have been the default.

==== ExportFilter: REGEX ARCHITECTURES

The export filter can be used to export build results from one
architecture to others. This is required when one architecture needs
packages from another architecture for building. The REGEX placeholder
must match the resulting binary name of the package. It will export it
to all listed scheduler architectures. Exported packages are not
used in the built architecture by default, add a `.` pseudo architecture
to also use them locally.

==== FileProvides: FILE PACKAGES

Due to memory consumption reasons dependencies to files as supported
by rpm are ignored by default. As a workaround, FileProvides can be
used to tell the systems which packages contain a file. The file needs
to have the full path.

==== HostArch: HOST_ARCH

This is used for cross builds. It defines the host architecture used for
building, while the scheduler architecture remains the target
architecture.

==== Ignore: PACKAGE_OR_DEPENDENCY

Ignore can be used to break dependencies. This can be useful to reduce
the number of needed packages or to break cyclic dependencies. If a
package is specified, all capabilities provided by the package are
ignored.

Be careful with this feature as breaking dependencies can have unwanted
results. It is usually better to limit its usage by also specify the
originating package as described in the following section.

==== Ignore: ORIGIN_PACKAGE:PACKAGE_OR_DEPENDENCY

Ignore a dependency coming from ORIGIN_PACKAGE. See the previous section
for more details.

==== Keep: PACKAGES

To eliminate build cycles the to-be-built packages are not installed by
default. Keep can be used to overwrite this behavior. It is usually needed
for packages like `make` that are used to build itself. Preinstalled
packages are automatically kept, as the package installation program needs
to work all the time.

==== OptFlags: TARGET_ARCH FLAGS (RPM only)

Optflags exports compiler flags to the build by adding lines to rpm's
`rpmrc` file. They will only have an effect when the spec file is using
`$RPM_OPT_FLAGS` or `%{optflags}`. The target architecture may be set
to `*` to affect all architectures.

==== Order: PACKAGE_A:PACKAGE_B

The build script takes care about the installation order if they are
defined via dependencies inside of the packages. However, there might be
dependency loops (reported during setup of the build system) or missing
dependencies. The Order statement can be used then to give a hint where
to break the loop.

The package in PACKAGE_A will get installed before the package in
PACKAGE_B.

==== Patterntype: TYPES

Defines the pattern format. Valid values are: `none` (default), `ymp`,
`comps`.

==== Prefer: PACKAGE

In case multiple packages satisfy a dependency, the dependency expansion
will fail. This is unlike like most package managing tools, which just
pick one of the package. It is done that way to provide reproducible
builds and reduce the chance of surprising changes when new packages
are added to the repository.
The Prefer: tag lists packages to be preferred in case a choice exists.
When the package name is prefixed with a minus sign, it is treated
as a de-prefer.

==== Prefer: ORIGIN_PACKAGE:PACKAGE

It is possible to define the prefer only when the dependency comes
from the specified originating package.

==== Preinstall: PACKAGE

This is used to specify packages needed to run the package installation
program. These packages are unpacked so that the native installation
program can be used to install the build environment.
Included scripts are not executed during this phase. However, these
packages will be re-installed later on including script execution.

==== PublishFlag: FLAG

CAUTION: OBS only

Flags which modify the behaviour during repository generation.

 * create_empty

Create a repository even with no content, but with meta data.

 * noearlykiwipublish

Only publish kiwi build results after entire repository has finished
building. Without this kiwi build results get published immediately
after the build is finished.

 * nofailedpackages

Block publishing if any build result was failed, broken, or
unresolvable. This is evaluated individually for each architecture. That
means, packages can be published for an architecture on which it builds,
even if a package fails to build on another architecture.

 * withreports

Also publish internal content tracking files (.report files).

 * ympdist:NAME (OBS 2.11 or later)

Defines the distversion to be used in group element of ymp files. This
is used by the installer to check if the repository is suitable for the
installed distribution.

==== PublishFilter: REGEXP [REGEXP]

CAUTION: OBS only

Limits the published binary packages in public repositories. Packages
that match any REGEXP will not be put into the exported repository.
There can be only one line of PublishFilter for historic reasons.
However, multiple REGEXP can be defined.

==== Repotype: TYPE[:OPTIONS]

Defines the repository format for published repositories. Valid values
are: `none`, `rpm-md`, `suse`, `debian`, `hdlist2`, `arch`, `staticlinks`
and vagrant.
The OPTIONS parameter depends on the repository type, for rpm-md the
known options are `legacy` to create the old rpm-md format, `deltainfo`
or `prestodelta` to create delta rpm packages, `rsyncable` to use
rsyncable gzip compression. To split the debug packages in an own
published repository the option `splitdebug:REPOSITORY_SUFFIX` can be
appended, e.g.:

    Repotype: splitdebug:-debuginfo

This results in a debuginfo package repository being created in parallel
to the package repository.

==== Required: PACKAGE

Specify a package that always is installed for package builds.
A change in one of these packages triggers a new build.

==== Runscripts: PACKAGE

Execute the scriptlets of the specified preinstalled package. Scriptlet
execution takes place after the preinstall phase, but before installing
the remaining packages.

==== Substitute: DEPENDENCY DEPENDENCY...

It is possible to replace to BuildRequires with other packages. This
will have only an effect on directly BuildRequired packages, not on
indirectly required packages.

==== Support: PACKAGE

Specify a package that always is installed for package builds.
Unlike `Required:`, a change in one of these packages does not trigger an
automatic rebuild.

This is useful for packages that most likely do not influence the build
result, for example `make` or `coreutils`.

==== Target: GNU_TRIPLET

Defines the target architecture via a gnu triplet (not the debian
architecture!). For example `arm-linux-gnueabihf` for armv7hl builds,
or `i686` for building i686 packages.

==== Type: TYPE

Build recipe type. This is the format of the file which provides the
build description (the "build recipe"). This is usually autodetected from
the binary type, but in some rare cases it may be needed to manually
configure the type. Currently the following types are understood:
`spec`, `dsc`, `arch`, `kiwi`, `livebuild`, `productcompose`, `preinstallimage`.

==== VMInstall: PACKAGE

Like Preinstall, but these packages get only installed when a virtual
machine like Xen or KVM is used for building. Usually packages like
`mount` are listed here.

=== Macros Definitions for the build configuration

You can use rpm macro definitions in the project config to improve
configurability.
Macros are defined with `%define` or `%global`. They are only known
in the project configuration but not available when the build is
done.

For example:

    %define _use_profiler 1

    %if 0%{?_use_profiler}
    Require: gprof
    %endif

Another example limiting a line to an architecture:

    %ifarch x86_64
    Support: x86_64_only_package
    %endif

=== Macro Definitions for the build process

To specify macros for the building process, use the `Macros:`
keyword. All lines after `Macros:` up to the end of the config
or to a `:Macros` line are used when parsing the spec file and
also made available to the build by copying them to the `.rpmmacros`
file in the build root.

Example:

    Macros:
    # add your macro definitions here
    %_hardened_build 0
    :Macros

=== Building with ccache or sccache

The usage of ccache or sccache can be enabled for each package by
seting the `useccache:PACKAGE` build flag.

The ccache package will automatically be installed and configured.
The directory /.ccache/ will be configured as cache
directory. To configure ccache, the file /.ccache/ccache.conf can be
modified as part of the build process by the $BUILD_USER environment
variable.

In some cases, there is no archive for the current package, such as when
the package was newly branched or when binaries were deleted. In these
cases, the system will check whether there is a package of the same name
built for the same architecture within one of the repositories
configured in the project's meta configuration. If so, the archive of
that package will be used. The repositories will be searched in the
order they are configured in the meta configuration, starting from the
top.

An alternative way to enable caching based on build dependencies is to
add "--enable-cache" as dependency, for example via a Substitute rule:

    Substitute: gcc-c++ gcc-c++ --enable-ccache

This will always enable ccache when a direct build depdency to gcc-c++
is required.

It is also possible to set the type, eg:

    Substitute: cargo cargo --enable-ccache=sccache

