=== Cross Architecture Build

Cross architecture builds specify two sets of repositories, one for the build environement
and one for the environment for the build result.

==== Terminology

The terminiology for this is unfortunatly not standarised and tools have conflicting
defintions. 

We use the following

=====  Host: The architecture build environment which executes the for example the compiler.

cmake is calling this HOST as well (eg. CMAKE_HOST_SYSTEM_PROCESSOR)

GNU tools (esp. the configure scripts generated by autoconf) is using BUILD as abbrevasion here

=====  Target: The architecture of the resulting binaries

cmake has this as default without any abbrevasion (eg. CMAKE_SYSTEM_PROCESSOR)

GNU tools (esp. the configure scripts generated by autoconf) is using HOST as abbrevasion here:
The "TARGET" defintion of them is something else, usually only used for compilers
where it defines the target architecture a from a cross build compiler.

===== The compatible terms can be found in the following table:

[width="15%"]
|=================================
|build || host  | target  |  -/-
|------||-------|---------|-------
|cmake || HOST  | default |  -/-
|GNU   || build | host    | target
|rpm   || build | target  |  -/-
|=================================

==== Example Calls in spec files for cross build

Note: the basic design of rpm was the GNU style, but it changed in the way that you have to
      specify the host architecture via %target macro on most distributions:

 ./configure --build=%build --host=%target

=== Repository setup

=== Build Config 
