=== Cross Architecture Build

Cross architecture builds specify two sets of repositories, one for the build environment
and one for the environment for the build result.

==== Terminology

The terminology for this is unfortunately not standardised and various tools have conflicting
definitions.

We use the following

=====  Host Native: The architecture build environment which executes for example the compiler.

cmake is calling this HOST as well (e.g. CMAKE_HOST_SYSTEM_PROCESSOR)

GNU tools (esp. the configure scripts generated by autoconf) use BUILD as abbreviation here

=====  Target: The architecture of the resulting binaries

cmake has this as default without any abbreviation (e.g. CMAKE_SYSTEM_PROCESSOR)

GNU tools (esp. the configure scripts generated by autoconf) use HOST as abbreviation here:
The "TARGET" definition of them is something else, usually only used for compilers
where it defines the target architecture of a cross build compiler.

===== The compatible terms can be found in the following table:

Unfortunately the naming of architecture areas is not consistent across the various build
tools. Please find the terminology mapping from our "build" script and other tools
in the list below.

[width="15%"]
|=================================
|pbuild|| host  | target  |  -/-
|cmake || HOST  | default |  -/-
|GNU   || build | host    | target
|rpm   || build | target  |  -/-
|=================================

Our build script just knows the host and target definition as described above.

cmake is similar, just uses different namings.

GNU (esp. in automake and autoconf) has actually three definitions, mainly for compiler
toolchain. "build" is the environment which creates binaries. Host are the resulting
binaries. And target is important when these binaries can build binaries as well for
another target.

==== Dependency handling

Dependencies need to be resolved always twice during a cross build. One time for the host
architecture and one time for the target architecture. Build dependencies of a package
get only installed for the target architecture by default.

However, global rules in the build configuration can be created to modify this behaviour.

===== AlsoNative: PACKAGES

Can be used to mark a package to get installed into the target and in the host system.

===== OnlyNative: PACKAGES

Can be used to install a package in the host system, but not in the target system. E.g.
for build tooling or code generators.

===== The target base system

All packages for a host system which are configured as "Required" get installed only in
the host system, but not in the target system. The reason behind is that these packages
are only supposed to be able to execute commands and therefore they are not needed in
the target environment. Only the build dependencies get installed there.

However, some distributions may lack a complete set of dependencies (esp. debian based).
In this case the base system for the target system can manually be configured via

Substitute: sysroot-packages PACKAGES

==== Example Calls in spec files for cross build

Note: the basic design of rpm was the GNU style, but it changed in the way that you have to
      specify the host architecture via %target macro on most distributions:

 ./configure --build=%build --host=%target
