=== Cross Architecture Build

Cross architecture builds specify two sets of repositories, one for the build environement
and one for the environment for the build result.

==== Terminology

The terminiology for this is unfortunatly not standarised and tools have conflicting
defintions. 

We use the following

=====  Host: The architecture build environment which executes the for example the compiler.

cmake is calling this HOST as well (eg. CMAKE_HOST_SYSTEM_PROCESSOR)

GNU tools (esp. the configure scripts generated by autoconf) is using BUILD as abbrevasion here

=====  Target: The architecture of the resulting binaries

cmake has this as default without any abbrevasion (eg. CMAKE_SYSTEM_PROCESSOR)

GNU tools (esp. the configure scripts generated by autoconf) is using HOST as abbrevasion here:
The "TARGET" defintion of them is something else, usually only used for compilers
where it defines the target architecture a from a cross build compiler.

===== The compatible terms can be found in the following table:

Unfortunatly the naming of architecture areas is not consistent via the various build
tooling. Please find the terminilogy mapping from our "build" script and other toolings
in the list below.

[width="15%"]
|=================================
|build || host  | target  |  -/-
|cmake || HOST  | default |  -/-
|GNU   || build | host    | target
|rpm   || build | target  |  -/-
|=================================

Our build script just knows the host and target definition as described above.

cmake is similar, just uses different namings.

GNU (esp. in automake and autoconf) has actually three definitions, mainly for compiler
toolchain. "build" is the environment which creates binaries. Host are the resulting
binaries. And target is important when these binaries can build binaries as well for
another target.

==== Dependency handling

Dependencies need to be resolved always twice during a cross build. One time for the host
architecture and one time for the target architecture. Build dependencies of a package
get only installed for the target architecture by default.

However, global rules in the build configuration can get created to modify this behaviour.

===== AlsoNative: PACKAGES

Can be used to mark a package to get installed into the target and in the host system.

===== OnlyNative: PACKAGES

Can be used to to install a package in the hostsystem, but not in the target system. Eg.
for build tooling or code generators.

===== The target base system

All packages for a host system which are configured as "Requrired" get installed only in
the host system, but not in the target system. The reason behind is that this packages
are only supposed to be able to execute commands and therefore they are not needed in
the target environment. Only the build dependencies get installed there.

However, some distributions may lack a complete set of dependencies (esp. debian based).
In this case the base system for the target system can manually get configured via

Substitute: sysroot-packages PACKAGES

==== Example Calls in spec files for cross build

Note: the basic design of rpm was the GNU style, but it changed in the way that you have to
      specify the host architecture via %target macro on most distributions:

 ./configure --build=%build --host=%target

=== Repository setup

=== Build Config 
