= pbuild Reference Guide
:toc:
:icons:
:numbered:
:website: https://www.geckito.org/

== Goals

== Design

The pbuild tool is a level above "the build script" called "build". "build" is handling single build jobs, while
pbuild is managing the dependencies between this build jobs. Both can get executed on any Linux system directly.

pbuild is processing local sources, but may download remote sources and binaries when referenced.
The local sources can get managed by any source revision management tool (eg. git).

The tasks of the build script are:
* Building a defined and reproducable environement for one build job
* Calling the build tool for any supported format (rpm, deb, kiwi image, docker, ...)
* Calling validations as provided by the build environement
* Extract build results
* Parse dependencies in binaries and build description files

The tasks of pbuild are:
* calculating the dependencies between the build jobs for a build order
* calculating the need of rebuilds due to changed sources or dependencies
* manage multiple running build jobs in the background
* organize build results on the disk
* download remote assets (sources or binaries)

=== Filesystem Structure

pbuild expects to get call in a directory where it's project configuration files are living. Package sources
live in directories inside of this project directory:

* Top directory
** Package A
*** source files
** Package B
*** source files
** ...
** _pbuild
** _config
** _build.<preset>
*** _jobhistory
*** Package A results
**** Build results
*** Package B results
**** Build results
*** .pbuild

==== _config

Can define build configurations. Usually defaults from a distribution are used, but this file can provide
additional rules. These define which packages need to become available in the build environment, macro definitions
and many more. See the build config topic for a detailed list.

==== _pbuild

This file defines one or more presets. A preset defines which 

* distribution configuration
* repositories
* hardware architectures

==== _build.<preset>

contains all binaries for the given preset. These are either downloaded or build local. Additional underscore prefixed 
files contain informations about the build history and current states of the build.

=== Important Options

pbuild does not need any parameters by default. It will build inside of KVM by default which can work
as user (non-root) in a proper environment. KVM will also ensure that the correct kernel is running
during build. However, builds in chroot or containern is also possible via

 --vm-type=chroot
 --vm-type=docker

Define the amount of provided memory in KVM via

 --vm-memory=MEGABYTES

The build environment disk space can get defined via

 --vm-disk-size=MEGABYTES

The KVM is fully isolated by default. This ensures that the build can become fully reproducibile and
also that no attack by using untrusted sources or binaries can happen. However, one may want to
use remote resources during build. In that case network access can get enabled via

 --vm-network

Keep in mind that this can get usually avoided by using remote assets instead.

=== Important Debugging Options

pbuild always creates a consistent state. That means it may not build actually anything, when the
last build result look current. One can enforce a rebuild by using

  --rebuild <PACKAGE>

The build log is by default only stored on disk. The live build log can become made available by 
using the

  --singlejob <PACKAGE>

option. This option might get combined with the option

  --singlejob <PACKAGE> --shell-after-fail

to get a shell prompt in case a build failure occurs. 

Alternative one can reuse last build enviroment or create a new one by using

  --shell

option. This will give a prompt after the environment has been initialized. It can be combined
with 

  -x binary_package

to get further tooling installed (eg. gdb or assumed missing dependencies for testing).

=== Remote Assets

Remote Assets can get defined inside of the build descriptions. These are resources from any remote
servers which will be downloaded and validated by pbuild.

Supported protocols are

 * http
 * https
 * git-http
 * git-https

The format depends on the build description format as described below.

==== rpm spec files

Source lines in spec files can get marked as remote assets. rpm is supporting to use an URL as source
definition already. A comment before such a line marks it as remote asset for pbuild.

 #!RemoteAsset: <SHA256SUM>
 Source: <URL>

The sha256 sum will be used to verify the download, but it is optional.

An alternative is to use the 

 #!RemoteAssetUrl: <URL>

marker, when the downloaded file shall not become part of the source rpm.

==== kiwi build description

The kiwi format is not supporting remote source specifications, but it can get specified via XML
comments. There needs to be a specification from where to download using

  <!-- OBS-RemoteAsset: <URL> -->

The resulting download file can get copied into the image using

  <!-- OBS-CopyToImage: <source> <destination> -->

The source specification is just the file name while the destination is the including the full
path to the file on the image.

==== Arch Linux PKGBUILD

==== FedPkg "sources" file

include::build_config.adoc[]

== Functionalities

=== package builds

Package builds are supported for rpm, deb, arch and their variations.

=== image builds

=== container builds

include::cross_arch_build.adoc[]






