=== Remote Assets

Remote Assets can be defined inside of the build descriptions. They are resources from a remote
servers and will be downloaded and validated by pbuild before the corresponding build is started.

Supported protocols for resources using an url are:

 * http
 * https
 * git+http
 * git+https

URLs for git support a revision specified as URL fragment. This can be a commit hash
or a branch name. For example git+https://github.com/openSUSE/example#main
The default is not to include the .git directory. If it is needed at build time, the
"withmeta" pseudo query parameter can be added.

This depends on the build description format as described below.

==== rpm spec files

Source lines in spec files can declare remote assets. Rpm is already supporting to use
an URL as source definition. A comment before such a line marks it as remote asset for pbuild:

 #!RemoteAsset
 Source: <URL>

It is also possible to specify a checksum to make sure that the asset is correct.

 #!RemoteAsset: <CHECKSUM>
 Source: <URL>

If the source file name should be different from the last component of the url path, the
url can also be specified as argument of the RemoteAsset line:

 #!RemoteAsset: <URL> [<CHECKSUM>]
 Source: <FILENAME>

A tar ball will be created at build time automatically, if the source is a directory
(like with git URLs) and the FILENAME is a tar ball.

==== kiwi build description

The kiwi format is not supporting remote source specifications, but they can be
specified via XML comments.

  <!-- OBS-RemoteAsset: <URL> -->

The resulting downloaded file can be copied into the image using

  <!-- OBS-CopyToImage: <source> <destination> -->

The kiwi profile name is added to container names by default. This can be
disabled via

  <!-- OBS-DoNotAppendProfileToContainername -->

==== Dockerfile description

Remote assets that will be downloaded before the build can be added via the
comment `#!RemoteAssetUrl: https://my.url/asset.tar`. `pbuild` will fetch the
asset before the build and will make it available in the buildroot so that the
asset can copied into the container as follows:

  ----
  #!RemoteAssetUrl: https://my.url/asset.tar
  COPY asset.tar .
  RUN tar -xvzf asset.tar
  ----

==== Arch Linux PKGBUILD

PKGBuild files already contain the needed URLs and Checksums, so no extra
treatment is needed.

==== FedPkg "sources" file

The sources file contains a list of file names with checksums. PBuild will
automatically download the missing files from a FedPkg Server that needs
to be configured in the project config via the "AssetsURL:" directive or set
with the "--assets" option.
