name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update packages repository
        run: |
          sudo apt-get update

      - name: Install libyaml-libyaml-perl
        run: |
          sudo apt-get install libyaml-libyaml-perl

      - name: Install debdiff for debtransform test
        run: |
          sudo apt-get install devscripts

      - name: Install dependencies for pbuild run
        run: |
          sudo apt-get install perl tar psmisc libwww-perl libxml-parser-perl libarchive-tools zstd

      - name: Test debtransform
        run: |
          export LC_ALL=C
          make test test-debtransform

      - name: Test pbuild myself
        run: |
          export BUILD_DIR=$PWD
          export PATH=$PWD:$PATH
          cd dist
          # always use latest branch during CI
          sed -i 's,#%{version},,' build.spec
          # --no-checks since chroot build inside of docker is not working
          pbuild --dist=tumbleweed --orphan --vm-type=podman --no-checks
